version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev 
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
    #stdin_open: true

  tests:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev 
    volumes: 
      - /app/node_modules
      - .:/app
    #stdin_open: true
    command: ["npm","run","test"]
